// ==============================================================
// LeadsPage — inbound release-alert, wine-club interest, and
// reservation-request leads generated by consumers in the app.
//
// This is the highest-direct-revenue surface of the dashboard:
// each lead is a qualified prospect the winery can reach out to.
// ==============================================================

import { useEffect, useMemo, useState } from "react";
import {
  Bell, Heart, CalendarDays, Mail, Users, Check, X,
  Inbox, Filter, MessageSquare, Lock
} from "lucide-react";
import { getWineryLeads, updateLeadStatus } from "../../firebaseClient.js";

const TYPE_META = {
  release_alert: {
    label: "Release alert",
    icon: Bell,
    color: "bg-purple-50 text-purple-700",
    desc: "Wants to hear about new releases",
  },
  club_interest: {
    label: "Wine club",
    icon: Heart,
    color: "bg-rose-50 text-rose-700",
    desc: "Interested in joining your wine club",
  },
  reservation_request: {
    label: "Reservation",
    icon: CalendarDays,
    color: "bg-amber-50 text-amber-700",
    desc: "Wants to book a tasting",
  },
};

const STATUS_STYLE = {
  new: "bg-blue-50 text-blue-700 border-blue-200",
  contacted: "bg-gray-50 text-gray-600 border-gray-200",
  converted: "bg-green-50 text-green-700 border-green-200",
  dismissed: "bg-gray-100 text-gray-400 border-gray-200",
};

function fmtDate(ts) {
  try {
    const d = ts?.toDate?.() || (ts ? new Date(ts) : null);
    if (!d || isNaN(d)) return "—";
    return d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "2-digit" });
  } catch { return "—"; }
}

export default function LeadsPage({ winery, tier }) {
  const [leads, setLeads] = useState(null);
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [busyId, setBusyId] = useState("");

  const isPro = tier === "pro";
  const wineryId = winery?.id ?? winery?.wineryId;

  useEffect(() => {
    if (!wineryId) { setLeads([]); return; }
    let cancelled = false;
    getWineryLeads(wineryId)
      .then(list => { if (!cancelled) setLeads(list); })
      .catch(() => { if (!cancelled) setLeads([]); });
    return () => { cancelled = true; };
  }, [wineryId]);

  const filtered = useMemo(() => {
    if (!leads) return [];
    return leads.filter(l => {
      if (typeFilter !== "all" && l.type !== typeFilter) return false;
      if (statusFilter !== "all" && (l.status || "new") !== statusFilter) return false;
      return true;
    });
  }, [leads, typeFilter, statusFilter]);

  const counts = useMemo(() => {
    if (!leads) return { total: 0, new: 0, byType: {} };
    const byType = {};
    let newCount = 0;
    for (const l of leads) {
      byType[l.type] = (byType[l.type] || 0) + 1;
      if ((l.status || "new") === "new") newCount += 1;
    }
    return { total: leads.length, new: newCount, byType };
  }, [leads]);

  const setStatus = async (lead, status) => {
    setBusyId(lead.id);
    try {
      await updateLeadStatus(lead.id, status);
      setLeads(prev => prev.map(l => l.id === lead.id ? { ...l, status } : l));
    } catch (e) {
      console.error("Lead status update failed:", e);
    } finally {
      setBusyId("");
    }
  };

  if (!isPro) {
    return (
      <div className="space-y-5">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Leads</h2>
          <p className="text-xs text-gray-400">Release alerts, wine-club interest, and reservation requests</p>
        </div>
        <div className="relative bg-white rounded-2xl border border-gray-100 p-10 text-center">
          <div className="w-14 h-14 rounded-2xl bg-purple-50 flex items-center justify-center mx-auto mb-4">
            <Lock className="w-6 h-6 text-purple-600" />
          </div>
          <h3 className="text-base font-bold text-gray-900 mb-1">Leads is a Pro feature</h3>
          <p className="text-xs text-gray-500 max-w-sm mx-auto mb-4">
            See every customer who tapped "notify me about releases", "I'm interested in the wine club",
            or requested a tasting reservation. Includes name, email, party size, and requested date.
          </p>
          <button className="px-4 py-2 bg-purple-600 text-white text-xs font-semibold rounded-lg">Upgrade to Pro</button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Leads</h2>
          <p className="text-xs text-gray-400">Inbound interest from Sip805 customers</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="px-3 py-1.5 rounded-lg bg-blue-50 text-blue-700 text-xs font-semibold">
            {counts.new} new
          </div>
          <div className="px-3 py-1.5 rounded-lg bg-gray-100 text-gray-700 text-xs font-semibold">
            {counts.total} total
          </div>
        </div>
      </div>

      {/* Filter chips */}
      <div className="flex flex-wrap gap-2">
        <div className="flex items-center gap-1 text-xs text-gray-400 pr-1">
          <Filter className="w-3.5 h-3.5" /> Type:
        </div>
        {["all", "release_alert", "club_interest", "reservation_request"].map(t => (
          <button key={t} onClick={() => setTypeFilter(t)}
            className={`px-2.5 py-1 rounded-full text-xs font-medium border transition ${
              typeFilter === t ? "bg-purple-600 text-white border-purple-600" : "bg-white text-gray-600 border-gray-200"
            }`}>
            {t === "all" ? "All types" : TYPE_META[t]?.label}
            {t !== "all" && counts.byType[t] ? ` · ${counts.byType[t]}` : ""}
          </button>
        ))}
      </div>
      <div className="flex flex-wrap gap-2 -mt-2">
        <div className="flex items-center gap-1 text-xs text-gray-400 pr-1">Status:</div>
        {["all", "new", "contacted", "converted", "dismissed"].map(s => (
          <button key={s} onClick={() => setStatusFilter(s)}
            className={`px-2.5 py-1 rounded-full text-xs font-medium border transition ${
              statusFilter === s ? "bg-gray-900 text-white border-gray-900" : "bg-white text-gray-600 border-gray-200"
            }`}>
            {s === "all" ? "All" : s.charAt(0).toUpperCase() + s.slice(1)}
          </button>
        ))}
      </div>

      {leads === null && (
        <div className="bg-white rounded-2xl border border-gray-100 p-6 text-center text-sm text-gray-400">Loading…</div>
      )}

      {leads !== null && filtered.length === 0 && (
        <div className="bg-white rounded-2xl border border-gray-100 p-10 text-center">
          <Inbox className="w-10 h-10 text-gray-200 mx-auto mb-2" />
          <p className="text-sm text-gray-400">No leads match the current filters.</p>
        </div>
      )}

      <div className="space-y-2">
        {filtered.map(lead => {
          const meta = TYPE_META[lead.type] || TYPE_META.release_alert;
          const Icon = meta.icon;
          const status = lead.status || "new";
          return (
            <div key={lead.id} className="bg-white rounded-2xl border border-gray-100 p-4">
              <div className="flex items-start gap-3">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 ${meta.color}`}>
                  <Icon className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center flex-wrap gap-2">
                    <span className="text-sm font-semibold text-gray-900">
                      {lead.userName || lead.userEmail || "Anonymous"}
                    </span>
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${STATUS_STYLE[status]}`}>
                      {status}
                    </span>
                    <span className="text-[11px] text-gray-400">{meta.label}</span>
                    <span className="text-[11px] text-gray-400">· {fmtDate(lead.createdAt)}</span>
                  </div>

                  {lead.userEmail && (
                    <a href={`mailto:${lead.userEmail}`} className="mt-1 inline-flex items-center gap-1 text-[11px] text-purple-600 hover:underline">
                      <Mail className="w-3 h-3" /> {lead.userEmail}
                    </a>
                  )}

                  {lead.type === "reservation_request" && (
                    <div className="mt-2 flex flex-wrap gap-3 text-[11px] text-gray-600">
                      {lead.requestedDate && (
                        <span className="inline-flex items-center gap-1">
                          <CalendarDays className="w-3 h-3" /> {lead.requestedDate}
                        </span>
                      )}
                      {lead.partySize && (
                        <span className="inline-flex items-center gap-1">
                          <Users className="w-3 h-3" /> Party of {lead.partySize}
                        </span>
                      )}
                    </div>
                  )}

                  {lead.message && (
                    <div className="mt-2 flex gap-1.5 text-xs text-gray-500">
                      <MessageSquare className="w-3 h-3 mt-0.5 flex-shrink-0 text-gray-300" />
                      <span className="leading-snug">{lead.message}</span>
                    </div>
                  )}

                  <div className="mt-3 flex flex-wrap gap-1.5">
                    <button
                      onClick={() => setStatus(lead, "contacted")}
                      disabled={busyId === lead.id || status === "contacted"}
                      className="px-2.5 py-1 rounded-lg bg-gray-100 text-gray-700 text-[11px] font-semibold disabled:opacity-50">
                      Mark contacted
                    </button>
                    <button
                      onClick={() => setStatus(lead, "converted")}
                      disabled={busyId === lead.id || status === "converted"}
                      className="px-2.5 py-1 rounded-lg bg-green-50 text-green-700 text-[11px] font-semibold disabled:opacity-50 inline-flex items-center gap-1">
                      <Check className="w-3 h-3" /> Converted
                    </button>
                    <button
                      onClick={() => setStatus(lead, "dismissed")}
                      disabled={busyId === lead.id || status === "dismissed"}
                      className="px-2.5 py-1 rounded-lg bg-gray-50 text-gray-500 text-[11px] font-semibold disabled:opacity-50 inline-flex items-center gap-1">
                      <X className="w-3 h-3" /> Dismiss
                    </button>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
